---
title: "Host details: debian-debbie"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | debian-debbie |
| Operating system | Debian |
| OS version | 13.5 |
| OS family | Debian |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | skylake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/home/pk=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| CFLAGS | -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/home/pk=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| LDFLAGS | -Wl,-z,relro |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu) |
| clang | Debian clang version 19.1.7 (3+b1) |
| ffmpeg | ffmpeg version 7.1.4-0+deb13u1 Copyright (c) 2000-2026 the FFmpeg developers |
| gcc | gcc (Debian 14.2.0-19) 14.2.0 |
| gimp | GNU Image Manipulation Program version 3.0.4 |
| go | go version go1.24.4 linux/amd64 |
| imagemagick | Version: ImageMagick 7.1.1-43 Q16 x86_64 22550 https://imagemagick.org |
| inkscape | Inkscape 1.4 (e7c3feb100, 2024-10-09) |
| kernel | 6.12.90+deb13-amd64 |
| lld | not installed |
| node | not installed |
| numpy | 2.2.4 |
| openssl | OpenSSL 3.5.6 7 Apr 2026 (Library: OpenSSL 3.5.6 7 Apr 2026) |
| perl | This is perl 5, version 40, subversion 1 (v5.40.1) built for x86_64-linux-gnu-thread-multi |
| python | Python 3.13.5 |
| ruby | not installed |
| rustc | rustc 1.85.0 (4d91de4e4 2025-02-17) (built from a source tarball) |
| sqlite3 | 3.46.1 2024-08-13 09:16:08 c9c2ab54ba1f5f46360f1b4f35d849cd3f080e6fc2b6c60e91b16c63f69aalt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 6945 |
| cflags | -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/home/pk=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| common_flags | -g -O2 -Werror=implicit-function-declaration -ffile-prefix-map=/home/pk=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | -g -O2 -ffile-prefix-map=/home/pk=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| features | n/a |
| filesystem | tmpfs |
| gcc_config | default-pie=yes, default-ssp=no, lto-support=no, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | debian-debbie |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | -Wl,-z,relro |
| libc_variant | glibc |
| libc_version | 2.41 |
| makeflags | n/a |
| makeopts | n/a |
| march_native | skylake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | Debian |
| os_family | Debian |
| os_version | 13.5 |
| pgo_enabled | False |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | EEVDF |
| smt_active | False |
| swap_enabled | True |
| thp | always |
| versions | gcc=gcc (Debian 14.2.0-19) 14.2.0, clang=Debian clang version 19.1.7 (3+b1), rustc=rustc 1.85.0 (4d91de4e4 2025-02-17) (built from a source tarball), go=go version go1.24.4 linux/amd64, python=Python 3.13.5, ffmpeg=ffmpeg version 7.1.4-0+deb13u1 Copyright (c) 2000-2026 the FFmpeg developers, openssl=OpenSSL 3.5.6 7 Apr 2026 (Library: OpenSSL 3.5.6 7 Apr 2026), kernel=6.12.90+deb13-amd64, bash=GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu), 7z=, imagemagick=Version: ImageMagick 7.1.1-43 Q16 x86_64 22550 https://imagemagick.org, lld=not installed, sqlite3=3.46.1 2024-08-13 09:16:08 c9c2ab54ba1f5f46360f1b4f35d849cd3f080e6fc2b6c60e91b16c63f69aalt1 (64-bit), numpy=2.2.4, gimp=GNU Image Manipulation Program version 3.0.4, inkscape=Inkscape 1.4 (e7c3feb100, 2024-10-09), perl=This is perl 5, version 40, subversion 1 (v5.40.1) built for x86_64-linux-gnu-thread-multi, ruby=not installed, node=not installed |
| virt_type | kvm |
