---
title: "Host details: elementaryos-elen"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | elementaryos-elen |
| Operating system | Ubuntu |
| OS version | 8 |
| OS family | Debian |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | skylake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/pk=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| CFLAGS | -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/pk=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| LDFLAGS | -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu) |
| clang | Ubuntu clang version 18.1.3 (1ubuntu1) |
| ffmpeg | ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers |
| gcc | gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0 |
| gimp | GNU Image Manipulation Program version 2.10.36 |
| go | go version go1.22.2 linux/amd64 |
| imagemagick | Version: ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org |
| inkscape | Inkscape 1.2.2 (b0a8486541, 2022-12-01) |
| kernel | 6.17.0-29-generic |
| lld | not installed |
| node | not installed |
| numpy | 1.26.4 |
| openssl | OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024) |
| perl | This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-gnu-thread-multi |
| python | Python 3.12.3 |
| ruby | not installed |
| rustc | rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) |
| sqlite3 | 3.45.1 2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 4835 |
| cflags | -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/pk=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| common_flags | -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/pk=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/pk=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| features | n/a |
| filesystem | ext4 |
| gcc_config | default-pie=yes, default-ssp=no, lto-support=no, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | elementaryos-elen |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro |
| libc_variant | glibc |
| libc_version | 2.39 |
| makeflags | n/a |
| makeopts | n/a |
| march_native | skylake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | Ubuntu |
| os_family | Debian |
| os_version | 8 |
| pgo_enabled | False |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | True |
| thp | madvise |
| versions | gcc=gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, clang=Ubuntu clang version 18.1.3 (1ubuntu1), rustc=rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball), go=go version go1.22.2 linux/amd64, python=Python 3.12.3, ffmpeg=ffmpeg version 6.1.1-3ubuntu5 Copyright (c) 2000-2023 the FFmpeg developers, openssl=OpenSSL 3.0.13 30 Jan 2024 (Library: OpenSSL 3.0.13 30 Jan 2024), kernel=6.17.0-29-generic, bash=GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu), 7z=, imagemagick=Version: ImageMagick 6.9.12-98 Q16 x86_64 18038 https://legacy.imagemagick.org, lld=not installed, sqlite3=3.45.1 2024-01-30 16:01:20 e876e51a0ed5c5b3126f52e532044363a014bc594cfefa87ffb5b82257ccalt1 (64-bit), numpy=1.26.4, gimp=GNU Image Manipulation Program version 2.10.36, inkscape=Inkscape 1.2.2 (b0a8486541, 2022-12-01), perl=This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-gnu-thread-multi, ruby=not installed, node=not installed |
| virt_type | kvm |
