---
title: "Host details: fedora-nelli"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | fedora-nelli |
| Operating system | Fedora |
| OS version | 44 |
| OS family | RedHat |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | skylake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -O2 -g |
| CFLAGS | -O2 -g |
| LDFLAGS | %{build_ldflags} |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.3.9(1)-release (x86_64-redhat-linux-gnu) |
| clang | clang version 22.1.5 (Fedora 22.1.5-1.fc44) |
| ffmpeg | ffmpeg version 8.1.1 Copyright (c) 2000-2026 the FFmpeg developers |
| gcc | gcc (GCC) 16.1.1 20260515 (Red Hat 16.1.1-2) |
| gimp | GNU Image Manipulation Program version 3.2.4 |
| go | go version go1.26.3-X:nodwarf5 linux/amd64 |
| imagemagick | Version: ImageMagick 7.1.2-13 Q16-HDRI x86_64 23522 https://imagemagick.org |
| inkscape | Inkscape 1.4.4 (dcaf3e7d9e, 2026-05-05) |
| kernel | 7.0.10-200.fc44.x86_64 |
| lld | not installed |
| node | not installed |
| numpy | 2.4.6 |
| openssl | OpenSSL 3.5.5 27 Jan 2026 (Library: OpenSSL 3.5.5 27 Jan 2026) |
| perl | This is perl 5, version 42, subversion 2 (v5.42.2) built for x86_64-linux-thread-multi |
| python | Python 3.14.4 |
| ruby | ruby 4.0.1 (2026-01-13 revision e04267a14b) +PRISM [x86_64-linux] |
| rustc | rustc 1.95.0 (59807616e 2026-04-14) (Fedora 1.95.0-5.fc44) |
| sqlite3 | 3.51.2 2026-01-09 17:27:48 b270f8339eb13b504d0b2ba154ebca966b7dde08e40c3ed7d559749818cbalt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 5035 |
| cflags | -O2 -g |
| common_flags | -O2 -g |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | -O2 -g |
| features | n/a |
| filesystem | tmpfs |
| gcc_config | default-pie=no, default-ssp=no, lto-support=no, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | fedora-nelli |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | %{build_ldflags} |
| libc_variant | glibc |
| libc_version | 2.43 |
| makeflags | -j${RPM_BUILD_NCPUS} |
| makeopts | n/a |
| march_native | skylake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | Fedora |
| os_family | RedHat |
| os_version | 44 |
| pgo_enabled | False |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | True |
| thp | madvise |
| versions | gcc=gcc (GCC) 16.1.1 20260515 (Red Hat 16.1.1-2), clang=clang version 22.1.5 (Fedora 22.1.5-1.fc44), rustc=rustc 1.95.0 (59807616e 2026-04-14) (Fedora 1.95.0-5.fc44), go=go version go1.26.3-X:nodwarf5 linux/amd64, python=Python 3.14.4, ffmpeg=ffmpeg version 8.1.1 Copyright (c) 2000-2026 the FFmpeg developers, openssl=OpenSSL 3.5.5 27 Jan 2026 (Library: OpenSSL 3.5.5 27 Jan 2026), kernel=7.0.10-200.fc44.x86_64, bash=GNU bash, version 5.3.9(1)-release (x86_64-redhat-linux-gnu), 7z=, imagemagick=Version: ImageMagick 7.1.2-13 Q16-HDRI x86_64 23522 https://imagemagick.org, lld=not installed, sqlite3=3.51.2 2026-01-09 17:27:48 b270f8339eb13b504d0b2ba154ebca966b7dde08e40c3ed7d559749818cbalt1 (64-bit), numpy=2.4.6, gimp=GNU Image Manipulation Program version 3.2.4, inkscape=Inkscape 1.4.4 (dcaf3e7d9e, 2026-05-05), perl=This is perl 5, version 42, subversion 2 (v5.42.2) built for x86_64-linux-thread-multi, ruby=ruby 4.0.1 (2026-01-13 revision e04267a14b) +PRISM [x86_64-linux], node=not installed |
| virt_type | kvm |
