---
title: "Host details: gentoo-emily"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | gentoo-emily |
| Operating system | Gentoo |
| OS version | 2.18 |
| OS family | Gentoo |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | 12th Gen Intel(R) Core(TM) i7-1260P |
| -march=native | alderlake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | default/linux/amd64/23.0/hardened/systemd |
| Common flags | -O2 -march=x86-64 -mtune=generic -flto -fno-semantic-interposition -fvect-cost-model=cheap -floop-block -fgraphite-identity -floop-parallelize-all -pipe |
| CFLAGS | ${COMMON_FLAGS} ${WARNING_FLAGS} |
| LDFLAGS | ${COMMON_FLAGS} ${LDFLAGS} ${WARNING_FLAGS} |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu) |
| clang | clang version 21.1.8 |
| ffmpeg | ffmpeg version 8.1 Copyright (c) 2000-2026 the FFmpeg developers |
| gcc | gcc (Gentoo Hardened 15.2.1_p20260214 p5) 15.2.1 20260214 |
| gimp | GNU Image Manipulation Program version 3.2.4 |
| go | go version go1.26.2-X:nodwarf5 linux/amd64 |
| imagemagick | Version: ImageMagick 7.1.2-18 Q16-HDRI x86_64 23822 https://imagemagick.org |
| inkscape | Inkscape 1.4.3 (0d15f75042, 2025-12-25) |
| kernel | 6.18.32-p2-gentoo-dist-hardened |
| lld | not installed |
| node | v24.14.0 |
| numpy | 2.4.4 |
| openssl | OpenSSL 3.5.6 7 Apr 2026 (Library: OpenSSL 3.5.6 7 Apr 2026) |
| perl | This is perl 5, version 42, subversion 0 (v5.42.0) built for x86_64-linux |
| python | Python 3.13.13 |
| ruby | ruby 3.3.11 (2026-03-26 revision 1f2d15125a) [x86_64-linux] |
| rustc | rustc 1.93.1 (01f6ddf75 2026-02-11) |
| sqlite3 | 3.51.3 2026-03-13 10:38:09 737ae4a34738ffa0c3ff7f9bb18df914dd1cad163f28fd6b6e114a344fe6alt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 5098 |
| cflags | ${COMMON_FLAGS} ${WARNING_FLAGS} |
| common_flags | -O2 -march=x86-64 -mtune=generic -flto -fno-semantic-interposition -fvect-cost-model=cheap -floop-block -fgraphite-identity -floop-parallelize-all -pipe |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 2496 |
| cpu_model | 12th Gen Intel(R) Core(TM) i7-1260P |
| cxxflags | n/a |
| features | n/a |
| filesystem | tmpfs |
| gcc_config | default-pie=yes, default-ssp=yes, lto-support=yes |
| gentoo_profile | default/linux/amd64/23.0/hardened/systemd |
| hostname | gentoo-emily |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | ${COMMON_FLAGS} ${LDFLAGS} ${WARNING_FLAGS} |
| libc_variant | glibc |
| libc_version | 2.42 |
| makeflags | n/a |
| makeopts | n/a |
| march_native | alderlake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | Gentoo |
| os_family | Gentoo |
| os_version | 2.18 |
| pgo_enabled | True |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | True |
| thp | madvise |
| versions | gcc=gcc (Gentoo Hardened 15.2.1_p20260214 p5) 15.2.1 20260214, clang=clang version 21.1.8, rustc=rustc 1.93.1 (01f6ddf75 2026-02-11), go=go version go1.26.2-X:nodwarf5 linux/amd64, python=Python 3.13.13, ffmpeg=ffmpeg version 8.1 Copyright (c) 2000-2026 the FFmpeg developers, openssl=OpenSSL 3.5.6 7 Apr 2026 (Library: OpenSSL 3.5.6 7 Apr 2026), kernel=6.18.32-p2-gentoo-dist-hardened, bash=GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu), 7z=, imagemagick=Version: ImageMagick 7.1.2-18 Q16-HDRI x86_64 23822 https://imagemagick.org, lld=not installed, sqlite3=3.51.3 2026-03-13 10:38:09 737ae4a34738ffa0c3ff7f9bb18df914dd1cad163f28fd6b6e114a344fe6alt1 (64-bit), numpy=2.4.4, gimp=GNU Image Manipulation Program version 3.2.4, inkscape=Inkscape 1.4.3 (0d15f75042, 2025-12-25), perl=This is perl 5, version 42, subversion 0 (v5.42.0) built for x86_64-linux, ruby=ruby 3.3.11 (2026-03-26 revision 1f2d15125a) [x86_64-linux], node=v24.14.0 |
| virt_type | kvm |
