---
title: "Host details: manjaro-justene"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | manjaro-justene |
| Operating system | Archlinux |
| OS version | 26.1.0-pre |
| OS family | Archlinux |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | skylake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \ |
| CFLAGS | -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \ |
| LDFLAGS | -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \ |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu) |
| clang | clang version 22.1.5 |
| ffmpeg | ffmpeg version n8.1.1 Copyright (c) 2000-2026 the FFmpeg developers |
| gcc | gcc (GCC) 16.1.1 20260430 |
| gimp | not installed |
| go | go version go1.26.3-X:nodwarf5 linux/amd64 |
| imagemagick | Version: ImageMagick 7.1.2-23 Q16-HDRI x86_64 6c51b2de5:20260516 https://imagemagick.org |
| inkscape | not installed |
| kernel | 6.12.91-1-MANJARO |
| lld | not installed |
| node | not installed |
| numpy | 2.4.6 |
| openssl | OpenSSL 3.6.2 7 Apr 2026 (Library: OpenSSL 3.6.2 7 Apr 2026) |
| perl | This is perl 5, version 42, subversion 2 (v5.42.2) built for x86_64-linux-thread-multi |
| python | Python 3.14.5 |
| ruby | not installed |
| rustc | rustc 1.95.0 (59807616e 2026-04-14) (Arch Linux rust 1:1.95.0-1) |
| sqlite3 | 3.53.1 2026-05-05 10:34:17 c88b22011a54b4f6fbd149e9f8e4de77658ce58143a1af0e3785e4e64751alt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 6960 |
| cflags | -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \ |
| common_flags | -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \ |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | $CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS |
| distro_label | Manjaro Linux 26.1.0-pre |
| features | n/a |
| filesystem | tmpfs |
| gcc_config | default-pie=yes, default-ssp=yes, lto-support=yes, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | manjaro-justene |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \ |
| libc_variant | glibc |
| libc_version | 2.43 |
| makeflags | -j2 |
| makeopts | n/a |
| march_native | skylake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | Archlinux |
| os_family | Archlinux |
| os_version | 26.1.0-pre |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | False |
| thp | always |
| versions | gcc=gcc (GCC) 16.1.1 20260430, clang=clang version 22.1.5, rustc=rustc 1.95.0 (59807616e 2026-04-14) (Arch Linux rust 1:1.95.0-1), go=go version go1.26.3-X:nodwarf5 linux/amd64, python=Python 3.14.5, ffmpeg=ffmpeg version n8.1.1 Copyright (c) 2000-2026 the FFmpeg developers, openssl=OpenSSL 3.6.2 7 Apr 2026 (Library: OpenSSL 3.6.2 7 Apr 2026), kernel=6.12.91-1-MANJARO, bash=GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu), 7z=, imagemagick=Version: ImageMagick 7.1.2-23 Q16-HDRI x86_64 6c51b2de5:20260516 https://imagemagick.org, lld=not installed, sqlite3=3.53.1 2026-05-05 10:34:17 c88b22011a54b4f6fbd149e9f8e4de77658ce58143a1af0e3785e4e64751alt1 (64-bit), numpy=2.4.6, gimp=not installed, inkscape=not installed, perl=This is perl 5, version 42, subversion 2 (v5.42.2) built for x86_64-linux-thread-multi, ruby=not installed, node=not installed |
| virt_type | kvm |
