---
title: "Host details: opensuse-susan"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | opensuse-susan |
| Operating system | openSUSE Tumbleweed |
| OS version | 20260525 |
| OS family | Suse |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | skylake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables |
| CFLAGS | -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables |
| LDFLAGS | %{build_ldflags} |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.3.9(1)-release (x86_64-suse-linux) |
| clang | clang version 22.1.5 |
| ffmpeg | ffmpeg version 8.1.1 Copyright (c) 2000-2026 the FFmpeg developers |
| gcc | gcc (SUSE Linux) 15.2.1 20260202 |
| gimp | GNU Image Manipulation Program version 3.2.4 |
| go | go version go1.26.4 linux/amd64 |
| imagemagick | Version: ImageMagick 7.1.2-23 Q16-HDRI x86_64 24055 https://imagemagick.org |
| inkscape | Inkscape 1.4.4 (unknown) |
| kernel | 7.0.9-2-default |
| lld | not installed |
| node | not installed |
| numpy | 2.4.4 |
| openssl | OpenSSL 3.5.3 16 Sep 2025 (Library: OpenSSL 3.5.3 16 Sep 2025) |
| perl | This is perl 5, version 42, subversion 1 (v5.42.1) built for x86_64-linux-thread-multi |
| python | Python 3.13.13 |
| ruby | ruby 4.0.5 (2026-05-20 revision 64336ffd0e) +PRISM [x86_64-linux-gnu] |
| rustc | rustc 1.95.0 (59807616e 2026-04-14) (built from a source tarball) |
| sqlite3 | 3.53.1 2026-05-05 10:34:17 c88b22011a54b4f6fbd149e9f8e4de77658ce58143a1af0e3785e4e64751alt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 6980 |
| cflags | -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables |
| common_flags | -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | -O2 -g -m64 -fmessage-length=0 -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables |
| distro_label | openSUSE Tumbleweed |
| features | n/a |
| filesystem | tmpfs |
| gcc_config | default-pie=no, default-ssp=no, lto-support=no, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | opensuse-susan |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | %{build_ldflags} |
| libc_variant | glibc |
| libc_version | 2.43 |
| makeflags | -j${RPM_BUILD_NCPUS} |
| makeopts | n/a |
| march_native | skylake |
| mem_speed | n/a |
| mitigations | mitigations=auto |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | openSUSE Tumbleweed |
| os_family | Suse |
| os_version | 20260525 |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | True |
| thp | always |
| versions | gcc=gcc (SUSE Linux) 15.2.1 20260202, clang=clang version 22.1.5, rustc=rustc 1.95.0 (59807616e 2026-04-14) (built from a source tarball), go=go version go1.26.4 linux/amd64, python=Python 3.13.13, ffmpeg=ffmpeg version 8.1.1 Copyright (c) 2000-2026 the FFmpeg developers, openssl=OpenSSL 3.5.3 16 Sep 2025 (Library: OpenSSL 3.5.3 16 Sep 2025), kernel=7.0.9-2-default, bash=GNU bash, version 5.3.9(1)-release (x86_64-suse-linux), 7z=, imagemagick=Version: ImageMagick 7.1.2-23 Q16-HDRI x86_64 24055 https://imagemagick.org, lld=not installed, sqlite3=3.53.1 2026-05-05 10:34:17 c88b22011a54b4f6fbd149e9f8e4de77658ce58143a1af0e3785e4e64751alt1 (64-bit), numpy=2.4.4, gimp=GNU Image Manipulation Program version 3.2.4, inkscape=Inkscape 1.4.4 (unknown), perl=This is perl 5, version 42, subversion 1 (v5.42.1) built for x86_64-linux-thread-multi, ruby=ruby 4.0.5 (2026-05-20 revision 64336ffd0e) +PRISM [x86_64-linux-gnu], node=not installed |
| virt_type | kvm |
