---
title: "Host details: rhel8.10-nicole"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | rhel8.10-nicole |
| Operating system | RedHat |
| OS version | 8.10 |
| OS family | RedHat |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | n/a |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | %{build_cflags} |
| CFLAGS | %{build_cflags} |
| LDFLAGS | %{build_ldflags} |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | not installed |
| bash | GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu) |
| clang | not installed |
| ffmpeg | not installed |
| gcc | not installed |
| gimp | not installed |
| go | not installed |
| imagemagick | not installed |
| inkscape | not installed |
| kernel | 4.18.0-553.125.1.el8_10.x86_64 |
| lld | not installed |
| node | not installed |
| numpy | 1.14.3 |
| openssl | OpenSSL 1.1.1k  FIPS 25 Mar 2021 |
| perl | This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi |
| python | Python 3.6.8 |
| ruby | not installed |
| rustc | not installed |
| sqlite3 | 3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238alt1 |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 0 |
| cflags | %{build_cflags} |
| common_flags | %{build_cflags} |
| cpu_cache_l3 | 16384K |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | n/a |
| features | n/a |
| filesystem | xfs |
| gcc_config | default-pie=no, default-ssp=no, lto-support=no |
| gentoo_profile | n/a |
| hostname | rhel8.10-nicole |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | %{build_ldflags} |
| libc_variant | glibc |
| libc_version | 2.28 |
| makeflags | -j8 |
| makeopts | n/a |
| march_native | n/a |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | RedHat |
| os_family | RedHat |
| os_version | 8.10 |
| pgo_enabled | False |
| preempt_model | VOLUNTARY |
| rustflags | n/a |
| scheduler | CFS |
| smt_active | False |
| swap_enabled | True |
| thp | always |
| versions | gcc=not installed, clang=not installed, rustc=not installed, go=not installed, python=Python 3.6.8, ffmpeg=not installed, openssl=OpenSSL 1.1.1k  FIPS 25 Mar 2021, kernel=4.18.0-553.125.1.el8_10.x86_64, bash=GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu), 7z=not installed, imagemagick=not installed, lld=not installed, sqlite3=3.26.0 2018-12-01 12:34:55 bf8c1b2b7a5960c282e543b9c293686dccff272512d08865f4600fb58238alt1, numpy=1.14.3, gimp=not installed, inkscape=not installed, perl=This is perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi, ruby=not installed, node=not installed |
| virt_type | kvm |
