---
title: "Host details: rhel10.1-monika"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | rhel10.1-monika |
| Operating system | RedHat |
| OS version | 10.2 |
| OS family | RedHat |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| -march=native | skylake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -O2 -g |
| CFLAGS | -O2 -g |
| LDFLAGS | %{build_ldflags} |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | not installed |
| bash | GNU bash, version 5.2.26(1)-release (x86_64-redhat-linux-gnu) |
| clang | clang version 21.1.8 (Red Hat, Inc. 21.1.8-1.el10) |
| ffmpeg | not installed |
| gcc | gcc (GCC) 14.3.1 20251022 (Red Hat 14.3.1-4) |
| gimp | not installed |
| go | go version go1.26.2 (Red Hat 1.26.2-2.el10_2) linux/amd64 |
| imagemagick | not installed |
| inkscape | not installed |
| kernel | 6.12.0-211.16.1.el10_2.x86_64 |
| lld | not installed |
| node | not installed |
| numpy | 1.26.4 |
| openssl | OpenSSL 3.5.5 27 Jan 2026 (Library: OpenSSL 3.5.5 27 Jan 2026) |
| perl | This is perl 5, version 40, subversion 2 (v5.40.2) built for x86_64-linux-thread-multi |
| python | Python 3.12.13 |
| ruby | not installed |
| rustc | rustc 1.92.0 (ded5c06cf 2025-12-08) (Red Hat 1.92.0-1.el10) |
| sqlite3 | not installed |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 0 |
| cflags | -O2 -g |
| common_flags | -O2 -g |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 3000 |
| cpu_model | Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz |
| cxxflags | -O2 -g |
| features | n/a |
| filesystem | xfs |
| gcc_config | default-pie=no, default-ssp=no, lto-support=no, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | rhel10.1-monika |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | %{build_ldflags} |
| libc_variant | glibc |
| libc_version | 2.39 |
| makeflags | -j${RPM_BUILD_NCPUS} |
| makeopts | n/a |
| march_native | skylake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | RedHat |
| os_family | RedHat |
| os_version | 10.2 |
| pgo_enabled | False |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | True |
| thp | always |
| versions | gcc=gcc (GCC) 14.3.1 20251022 (Red Hat 14.3.1-4), clang=clang version 21.1.8 (Red Hat, Inc. 21.1.8-1.el10), rustc=rustc 1.92.0 (ded5c06cf 2025-12-08) (Red Hat 1.92.0-1.el10), go=go version go1.26.2 (Red Hat 1.26.2-2.el10_2) linux/amd64, python=Python 3.12.13, ffmpeg=not installed, openssl=OpenSSL 3.5.5 27 Jan 2026 (Library: OpenSSL 3.5.5 27 Jan 2026), kernel=6.12.0-211.16.1.el10_2.x86_64, bash=GNU bash, version 5.2.26(1)-release (x86_64-redhat-linux-gnu), 7z=not installed, imagemagick=not installed, lld=not installed, sqlite3=not installed, numpy=1.26.4, gimp=not installed, inkscape=not installed, perl=This is perl 5, version 40, subversion 2 (v5.40.2) built for x86_64-linux-thread-multi, ruby=not installed, node=not installed |
| virt_type | kvm |
