---
title: "Host details: ubuntu-faith"
format: html
---

## Identity and platform

| Field | Value |
| --- | --- |
| Hostname | ubuntu-faith |
| Operating system | Ubuntu |
| OS version | 26.04 |
| OS family | Debian |

## Hardware and runtime

| Field | Value |
| --- | --- |
| CPU model | 12th Gen Intel(R) Core(TM) i7-1260P |
| -march=native | alderlake |

## Build and tuning

| Field | Value |
| --- | --- |
| Gentoo profile | n/a |
| Common flags | -g -O2 -Werror=implicit-function-declaration -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/davek=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| CFLAGS | -g -O2 -Werror=implicit-function-declaration -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/davek=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| LDFLAGS | -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro |

## Tool versions

| Tool | Version |
| --- | --- |
| 7z | n/a |
| bash | GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu) |
| clang | Ubuntu clang version 21.1.8 (6ubuntu1) |
| ffmpeg | ffmpeg version 8.0.1-3ubuntu2 Copyright (c) 2000-2025 the FFmpeg developers |
| gcc | gcc (Ubuntu 15.2.0-16ubuntu1) 15.2.0 |
| gimp | GNU Image Manipulation Program version 3.2.2 |
| go | go version go1.26.0 linux/amd64 |
| imagemagick | Version: ImageMagick 7.1.2-18 Q16 x86_64 23822 https://imagemagick.org |
| inkscape | not installed |
| kernel | 7.0.0-15-generic |
| lld | not installed |
| node | not installed |
| numpy | 2.3.5 |
| openssl | OpenSSL 3.5.5 27 Jan 2026 (Library: OpenSSL 3.5.5 27 Jan 2026) |
| perl | This is perl 5, version 40, subversion 1 (v5.40.1) built for x86_64-linux-gnu-thread-multi |
| python | Python 3.14.4 |
| ruby | not installed |
| rustc | rustc 1.93.1 (01f6ddf75 2026-02-11) (built from a source tarball) |
| sqlite3 | 3.46.1 2024-08-13 09:16:08 c9c2ab54ba1f5f46360f1b4f35d849cd3f080e6fc2b6c60e91b16c63f69aalt1 (64-bit) |

## Full metadata dump

| Key | Value |
| --- | --- |
| calibration_mips | 7311 |
| cflags | -g -O2 -Werror=implicit-function-declaration -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/davek=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| common_flags | -g -O2 -Werror=implicit-function-declaration -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/davek=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| cpu_cache_l3 | 128 MiB (8 instances) |
| cpu_cores | 8 |
| cpu_flags_x86 | n/a |
| cpu_governor | unknown |
| cpu_mhz | 2496 |
| cpu_model | 12th Gen Intel(R) Core(TM) i7-1260P |
| cxxflags | -g -O2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ffile-prefix-map=/home/davek=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection |
| features | n/a |
| filesystem | tmpfs |
| gcc_config | default-pie=yes, default-ssp=no, lto-support=no, bootstrap-lto=yes |
| gentoo_profile | n/a |
| hostname | ubuntu-faith |
| io_scheduler | unknown |
| is_hypervisor | False |
| ldflags | -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro |
| libc_variant | glibc |
| libc_version | 2.43 |
| makeflags | n/a |
| makeopts | n/a |
| march_native | alderlake |
| mem_speed | n/a |
| mitigations | default |
| normalization_mode | platform-default |
| normalization_reduced | False |
| numa_nodes | 1 |
| os | Ubuntu |
| os_family | Debian |
| os_version | 26.04 |
| pgo_enabled | False |
| preempt_model | DYNAMIC |
| rustflags | n/a |
| scheduler | sched_ext |
| smt_active | False |
| swap_enabled | True |
| thp | madvise |
| versions | gcc=gcc (Ubuntu 15.2.0-16ubuntu1) 15.2.0, clang=Ubuntu clang version 21.1.8 (6ubuntu1), rustc=rustc 1.93.1 (01f6ddf75 2026-02-11) (built from a source tarball), go=go version go1.26.0 linux/amd64, python=Python 3.14.4, ffmpeg=ffmpeg version 8.0.1-3ubuntu2 Copyright (c) 2000-2025 the FFmpeg developers, openssl=OpenSSL 3.5.5 27 Jan 2026 (Library: OpenSSL 3.5.5 27 Jan 2026), kernel=7.0.0-15-generic, bash=GNU bash, version 5.3.9(1)-release (x86_64-pc-linux-gnu), 7z=, imagemagick=Version: ImageMagick 7.1.2-18 Q16 x86_64 23822 https://imagemagick.org, lld=not installed, sqlite3=3.46.1 2024-08-13 09:16:08 c9c2ab54ba1f5f46360f1b4f35d849cd3f080e6fc2b6c60e91b16c63f69aalt1 (64-bit), numpy=2.3.5, gimp=GNU Image Manipulation Program version 3.2.2, inkscape=not installed, perl=This is perl 5, version 40, subversion 1 (v5.40.1) built for x86_64-linux-gnu-thread-multi, ruby=not installed, node=not installed |
| virt_type | kvm |
