#!/usr/bin/env python3
"""
collapse_use_flags.py
~~~~~~~~~~~~~~~~~~~~~
Reads per-host USE-flag JSON facts collected by the collect_use_flags Ansible
role, then collapses them into group_vars/all/, group_vars/<group>/, and
host_vars/<host>/ YAML files using a greedy, least-specific-first strategy:

  1. If a flag/value is identical for EVERY host → group_vars/all/
  2. Else for each group (sorted largest-first) where all members agree →
       group_vars/<group>/
  3. Remaining host-unique flags → host_vars/<host>/

Domains handled:
  • global_use_flags  (USE="..." in make.conf)
  • use_expand        (VIDEO_CARDS, INPUT_DEVICES, CPU_FLAGS_X86, …)
  • build_profile     (CFLAGS, CXXFLAGS, LDFLAGS, MAKEOPTS, FEATURES)
  • package_use       (/etc/portage/package.use/*)
  • make_conf         (all remaining variable assignments in make.conf)
  • use_flag_types    (classifies global_use_flags as global/local/unknown)

Usage:
    python3 scripts/collapse_use_flags.py \\
        --facts-dir /tmp/ansible_use_flags_facts \\
        --output-dir /path/to/project \\
        [--dry-run] [--update]
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required.  Install it with:  pip install pyyaml", file=sys.stderr)
    sys.exit(1)

import re as _re
_SAFE_NAME = _re.compile(r'^[a-zA-Z0-9][a-zA-Z0-9._-]{0,127}$')


def _safe_path_component(name: str, kind: str) -> str:
    """Raise ValueError if name is unsafe to use as a filesystem path component."""
    if not name or '..' in name or '/' in name or '\\' in name:
        raise ValueError(f"Unsafe {kind} name: {name!r}")
    if not _SAFE_NAME.match(name):
        raise ValueError(f"Unsafe {kind} name: {name!r}")
    return name


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# USE_EXPAND variable names to extract from make.conf as flag-list domains.
USE_EXPAND_VARS = [
    "VIDEO_CARDS", "INPUT_DEVICES", "CPU_FLAGS_X86", "CPU_FLAGS_ARM",
    "L10N", "LINGUAS", "GRUB_PLATFORMS",
    "QEMU_SOFTMMU_TARGETS", "QEMU_USER_TARGETS",
    "PYTHON_TARGETS", "PYTHON_SINGLE_TARGET",
    "LUA_TARGETS", "LUA_SINGLE_TARGET",
    "RUBY_TARGETS", "PHP_TARGETS",
    "LIBREOFFICE_EXTENSIONS", "OFFICE_IMPLEMENTATION",
    "CALLIGRA_FEATURES", "COLLECTD_PLUGINS", "NETBEANS_MODULES",
]

# Build-profile variables (string-equality collapse with group support).
BUILD_VARS = ["CFLAGS", "CXXFLAGS", "LDFLAGS", "MAKEOPTS", "FEATURES"]

# Variables handled by dedicated domains — excluded from the make_conf domain.
_MAKE_CONF_SKIP_VARS = frozenset({"USE"} | set(USE_EXPAND_VARS) | set(BUILD_VARS))

# Type alias for the return value of every collapse_* function.
CollapseResult = tuple[dict, dict[str, dict], dict[str, dict]]


# ---------------------------------------------------------------------------
# YAML helpers
# ---------------------------------------------------------------------------

def _ordered_dump(data: Any, stream=None, **kwargs) -> str:
    """Dump YAML with a stable key order, 2-space indent, and indented sequences."""

    class _Dumper(yaml.Dumper):  # noqa: D101
        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow=flow, indentless=False)

    _Dumper.add_representer(
        dict,
        lambda dumper, d: dumper.represent_mapping(
            "tag:yaml.org,2002:map", sorted(d.items())
        ),
    )
    return yaml.dump(data, stream=stream, Dumper=_Dumper, default_flow_style=False,
                     allow_unicode=True, indent=2, **kwargs)


def _load_yaml(path: Path) -> dict:
    if path.exists():
        with path.open() as fh:
            return yaml.safe_load(fh) or {}
    return {}


def _write_yaml(path: Path, data: dict, dry_run: bool, update: bool) -> bool:
    """Write *data* to *path* as YAML.  Returns True when file is changed."""
    if not data:
        return False

    if update and path.exists():
        existing = _load_yaml(path)
        existing.update(data)
        data = existing

    content = "---\n# Generated by scripts/collapse_use_flags.py — do not edit manually.\n"
    content += _ordered_dump(data)

    changed = not path.exists() or path.read_text() != content
    if changed:
        if dry_run:
            print(f"[DRY-RUN] Would write {path}")
            _diff_yaml(path, content)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"[WRITE] {path}")
    return changed


def _diff_yaml(path: Path, new_content: str) -> None:
    old = path.read_text().splitlines(keepends=True) if path.exists() else []
    new = new_content.splitlines(keepends=True)
    diff = difflib.unified_diff(old, new, fromfile=str(path), tofile=str(path) + ".new")
    sys.stdout.writelines(diff)


# ---------------------------------------------------------------------------
# make.conf parsing
# ---------------------------------------------------------------------------

_MAKE_CONF_VAR_RE = re.compile(
    r'^([A-Z_][A-Z0-9_]*)='
    r'(?:"([^"]*)"|\'([^\']*)\'|([^#\n]*))',
    re.MULTILINE,
)


def parse_make_conf(text: str) -> dict[str, str]:
    """Extract all shell variable assignments from cleaned make.conf text."""
    result: dict[str, str] = {}
    for m in _MAKE_CONF_VAR_RE.finditer(text):
        name = m.group(1)
        if m.group(2) is not None:
            value = m.group(2)          # double-quoted
        elif m.group(3) is not None:
            value = m.group(3)          # single-quoted
        else:
            value = (m.group(4) or "").strip()  # unquoted
        result[name] = value
    return result


# ---------------------------------------------------------------------------
# Fact loading and preprocessing
# ---------------------------------------------------------------------------

def load_facts(facts_dir: Path) -> dict[str, dict]:
    """Return mapping hostname → fact dict."""
    facts: dict[str, dict] = {}
    for json_file in sorted(facts_dir.glob("*.json")):
        host = json_file.stem
        with json_file.open() as fh:
            facts[host] = json.load(fh)
    if not facts:
        print(f"WARNING: No fact files found in {facts_dir}", file=sys.stderr)
    return facts


def build_group_map(facts: dict[str, dict]) -> dict[str, list[str]]:
    """Return mapping group_name → [hostnames].  Excludes 'all' (handled separately)."""
    groups: dict[str, list[str]] = defaultdict(list)
    for host, data in facts.items():
        for grp in data.get("groups", []):
            if grp != "all":
                groups[grp].append(host)
    return dict(groups)


def preprocess_facts(facts: dict[str, dict]) -> None:
    """Derive global_use_flags, use_expand, and build_profile from make_conf_raw.

    Modifies *facts* in place.  Uses ``setdefault`` so that legacy JSON
    formats that already contain these fields are not overwritten.
    """
    for data in facts.values():
        mc = parse_make_conf(data.get("make_conf_raw", ""))

        # global_use_flags: split the USE value into a list
        use_value = mc.get("USE", "")
        data.setdefault("global_use_flags", use_value.split() if use_value else [])

        # use_expand: split each USE_EXPAND var into a list
        use_expand: dict[str, list[str]] = {}
        for var in USE_EXPAND_VARS:
            tokens = mc.get(var, "").split()
            if tokens:
                use_expand[var] = tokens
        data.setdefault("use_expand", use_expand)

        # build_profile: raw string values
        build_profile: dict[str, str] = {}
        for var in BUILD_VARS:
            val = mc.get(var, "")
            if val:
                build_profile[var] = val
        data.setdefault("build_profile", build_profile)


def promote_wildcard_package_use(facts: dict[str, dict]) -> None:
    """Move ``*/*`` entries from ``package_use`` into the correct domain.

    Tokens prefixed with a known USE_EXPAND variable name followed by ``:``
    (e.g. ``VIDEO_CARDS: dummy intel``) are routed to ``use_expand``.
    Plain tokens (e.g. ``lto``, ``-wayland``) become ``global_use_flags``.

    Modifies *facts* in place.
    """
    expand_names = frozenset(USE_EXPAND_VARS)
    for data in facts.values():
        wildcard_tokens = data.get("package_use", {}).pop("*/*", None)
        if not wildcard_tokens:
            continue

        plain_flags: list[str] = []
        current_var: str | None = None
        expand = dict(data.get("use_expand", {}))

        for token in wildcard_tokens:
            bare = token.rstrip(":")
            if bare in expand_names and token.endswith(":"):
                current_var = bare
                expand.setdefault(current_var, [])
            elif current_var is not None:
                expand[current_var].append(token)
            else:
                plain_flags.append(token)

        if plain_flags:
            combined = _flags_to_set(data.get("global_use_flags", [])) | _flags_to_set(plain_flags)
            data["global_use_flags"] = _set_to_list(combined)

        data["use_expand"] = expand


# ---------------------------------------------------------------------------
# Collapse helpers
# ---------------------------------------------------------------------------

def _intersection_of_sets(host_sets: list[frozenset]) -> frozenset:
    if not host_sets:
        return frozenset()
    return frozenset.intersection(*host_sets)


def _flags_to_set(flags: list[str]) -> frozenset[str]:
    """Normalise a flag list — bare names are treated as '+name'."""
    out = set()
    for f in flags:
        f = f.strip()
        if not f:
            continue
        if f.startswith(("-", "+")):
            out.add(f)
        else:
            out.add("+" + f)
    return frozenset(out)


def _set_to_list(flags: frozenset[str]) -> list[str]:
    """Sort: enabled flags first (alphabetically), then disabled."""
    enabled = sorted(f for f in flags if not f.startswith("-"))
    disabled = sorted(f for f in flags if f.startswith("-"))
    return enabled + disabled


def _collapse_flag_sets(
    per_host: dict[str, frozenset[str]],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> tuple[frozenset[str], dict[str, frozenset[str]], dict[str, frozenset[str]]]:
    """Three-tier collapse for flag sets using set intersection.

    Returns (common, group_flags, remainder) where:
      - common: flags present on every host
      - group_flags: group → additional flags common within that group
      - remainder: host → flags unique to that host
    """
    common = _intersection_of_sets(list(per_host.values()))
    remainder: dict[str, frozenset[str]] = {h: per_host[h] - common for h in all_hosts}

    group_flags: dict[str, frozenset[str]] = {}
    for grp, members in sorted(group_map.items(), key=lambda kv: -len(kv[1])):
        members_in_facts = [m for m in members if m in remainder]
        if not members_in_facts:
            continue
        grp_common = _intersection_of_sets([remainder[m] for m in members_in_facts])
        if grp_common:
            group_flags[grp] = grp_common
            for m in members_in_facts:
                remainder[m] -= grp_common

    return common, group_flags, remainder


# ---------------------------------------------------------------------------
# Domain: global USE flags
# ---------------------------------------------------------------------------

def collapse_global_use(
    facts: dict[str, dict],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> CollapseResult:
    per_host = {h: _flags_to_set(facts[h].get("global_use_flags", [])) for h in all_hosts}
    common, grp_flags, remainder = _collapse_flag_sets(per_host, group_map, all_hosts)

    key = "global_use_flags"
    all_data = {key: _set_to_list(common)} if common else {}
    group_data = {g: {key: _set_to_list(f)} for g, f in grp_flags.items() if f}
    host_data = {h: {key: _set_to_list(f)} for h, f in remainder.items() if f}
    return all_data, group_data, host_data


# ---------------------------------------------------------------------------
# Domain: USE_EXPAND variables
# ---------------------------------------------------------------------------

def collapse_use_expand(
    facts: dict[str, dict],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> CollapseResult:
    """Collapse each USE_EXPAND var independently, then merge into dicts."""
    all_expand_vars: set[str] = set()
    for h in all_hosts:
        all_expand_vars.update(facts[h].get("use_expand", {}).keys())

    all_expand: dict[str, list] = {}
    group_expand: dict[str, dict[str, list]] = defaultdict(dict)
    host_expand: dict[str, dict[str, list]] = defaultdict(dict)

    for var in sorted(all_expand_vars):
        per_host = {
            h: _flags_to_set(facts[h].get("use_expand", {}).get(var, []))
            for h in all_hosts
        }
        common, grp_flags, remainder = _collapse_flag_sets(per_host, group_map, all_hosts)

        if common:
            all_expand[var] = _set_to_list(common)
        for g, f in grp_flags.items():
            if f:
                group_expand[g][var] = _set_to_list(f)
        for h, f in remainder.items():
            if f:
                host_expand[h][var] = _set_to_list(f)

    key = "use_expand"
    all_data = {key: all_expand} if all_expand else {}
    group_data = {g: {key: d} for g, d in group_expand.items() if d}
    host_data = {h: {key: d} for h, d in host_expand.items() if d}
    return all_data, group_data, host_data


# ---------------------------------------------------------------------------
# Domain: build_profile (CFLAGS, FEATURES, …)
# ---------------------------------------------------------------------------

def collapse_build_profile(
    facts: dict[str, dict],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> CollapseResult:
    """Collapse string-valued build profile vars (exact-match equality)."""
    all_vars: set[str] = set()
    for h in all_hosts:
        all_vars.update(facts[h].get("build_profile", {}).keys())

    all_bp: dict[str, str] = {}
    group_bp: dict[str, dict[str, str]] = defaultdict(dict)
    host_bp: dict[str, dict[str, str]] = defaultdict(dict)

    sorted_groups = sorted(group_map.items(), key=lambda kv: -len(kv[1]))
    for var in sorted(all_vars):
        values: dict[str, str] = {
            h: facts[h].get("build_profile", {}).get(var, "") for h in all_hosts
        }
        unique_vals = set(values.values())

        if len(unique_vals) == 1:
            all_bp[var] = unique_vals.pop()
            continue

        assigned: set[str] = set()
        for grp, members in sorted_groups:
            members_in_facts = [m for m in members if m in values and m not in assigned]
            if not members_in_facts:
                continue
            grp_vals = set(values[m] for m in members_in_facts)
            if len(grp_vals) == 1:
                group_bp[grp][var] = grp_vals.pop()
                assigned.update(members_in_facts)

        for h in all_hosts:
            if h not in assigned:
                host_bp[h][var] = values[h]

    key = "build_profile"
    all_data = {key: all_bp} if all_bp else {}
    group_data = {g: {key: d} for g, d in group_bp.items() if d}
    host_data = {h: {key: d} for h, d in host_bp.items() if d}
    return all_data, group_data, host_data


# ---------------------------------------------------------------------------
# Domain: package_use
# ---------------------------------------------------------------------------

def collapse_package_use(
    facts: dict[str, dict],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> CollapseResult:
    """Collapse per-package USE flags.

    A package entry goes to the least-specific group where EVERY member has
    the exact same (non-empty) flag list for that package.  Members that do
    not mention the atom at all prevent the atom from collapsing to that group.
    """
    all_atoms: set[str] = set()
    for h in all_hosts:
        all_atoms.update(facts[h].get("package_use", {}).keys())

    all_pkg: dict[str, list] = {}
    group_pkg: dict[str, dict[str, list]] = defaultdict(dict)
    host_pkg: dict[str, dict[str, list]] = defaultdict(dict)

    sorted_groups = sorted(group_map.items(), key=lambda kv: -len(kv[1]))
    for atom in sorted(all_atoms):
        per_host = {
            h: _flags_to_set(facts[h].get("package_use", {}).get(atom, []))
            for h in all_hosts
        }

        # Only hosts that actually mention this atom
        relevant = {h: f for h, f in per_host.items() if f}
        if not relevant:
            continue

        unique_sets = set(relevant.values())
        if len(unique_sets) == 1 and len(relevant) == len(all_hosts):
            all_pkg[atom] = _set_to_list(unique_sets.pop())
            continue

        # A group can claim this atom only if ALL its members mention it
        # with an identical flag set.
        assigned: set[str] = set()
        for grp, members in sorted_groups:
            unassigned_members = [m for m in members if m not in assigned]
            if not unassigned_members:
                continue
            if not all(m in relevant for m in unassigned_members):
                continue
            grp_sets = set(relevant[m] for m in unassigned_members)
            if len(grp_sets) == 1:
                group_pkg[grp][atom] = _set_to_list(grp_sets.pop())
                assigned.update(unassigned_members)

        for h in all_hosts:
            if h not in assigned and h in relevant:
                host_pkg[h][atom] = _set_to_list(relevant[h])

    key = "package_use"
    all_data = {key: all_pkg} if all_pkg else {}
    group_data = {g: {key: d} for g, d in group_pkg.items() if d}
    host_data = {h: {key: d} for h, d in host_pkg.items() if d}
    return all_data, group_data, host_data


# ---------------------------------------------------------------------------
# Domain: make_conf (remaining variable assignments from make.conf)
# ---------------------------------------------------------------------------

def collapse_make_conf(
    facts: dict[str, dict],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> CollapseResult:
    """Collapse make.conf variables not handled by other domains.

    Variables in USE, USE_EXPAND, and BUILD are skipped — they have dedicated
    collapse functions.  Remaining variables use all-or-host collapsing.
    """
    per_host = {h: parse_make_conf(facts[h].get("make_conf_raw", "")) for h in all_hosts}

    all_vars: set[str] = set()
    for d in per_host.values():
        all_vars.update(d.keys())

    all_mc: dict[str, str] = {}
    host_mc: dict[str, dict[str, str]] = defaultdict(dict)

    for var in sorted(all_vars):
        if var in _MAKE_CONF_SKIP_VARS:
            continue
        present = {h: per_host[h][var] for h in all_hosts if var in per_host[h]}
        if len(present) == len(all_hosts) and len(set(present.values())) == 1:
            all_mc[var] = next(iter(present.values()))
        else:
            for h, v in present.items():
                host_mc[h][var] = v

    key = "make_conf"
    all_data = {key: all_mc} if all_mc else {}
    host_data = {h: {key: d} for h, d in host_mc.items() if d}
    return all_data, {}, host_data


# ---------------------------------------------------------------------------
# Domain: use_flag_types
# ---------------------------------------------------------------------------

def collapse_use_flag_types(
    facts: dict[str, dict],
    group_map: dict[str, list[str]],
    all_hosts: list[str],
) -> CollapseResult:
    """Classify each flag in global_use_flags as global, local, or unknown.

    • global  – listed in the Portage profile's use.desc (broadly applicable)
    • local   – listed only in use.local.desc (package-specific)
    • unknown – not found in either profile file (custom / typo)

    Always written to group_vars/all/ (the classification is a property of
    the Portage tree, not of individual hosts).
    """
    # Build a merged set of profile flags from all hosts.
    profile_global: set[str] = set()
    profile_local: set[str] = set()
    all_flags: list[str] = []

    for h in all_hosts:
        profile_global.update(facts[h].get("profile_global_flags", []))
        profile_local.update(facts[h].get("profile_local_flags", []))
        for flag in facts[h].get("global_use_flags", []):
            if flag not in all_flags:
                all_flags.append(flag)

    buckets: dict[str, list[str]] = {"global": [], "local": [], "unknown": []}
    for flag in all_flags:
        name = flag.lstrip("+-")
        if name in profile_global:
            buckets["global"].append(flag)
        elif name in profile_local:
            buckets["local"].append(flag)
        else:
            buckets["unknown"].append(flag)

    merged = {k: v for k, v in buckets.items() if v}
    return ({"use_flag_types": merged} if merged else {}), {}, {}


# ---------------------------------------------------------------------------
# Deep merge helpers
# ---------------------------------------------------------------------------

def _deep_merge(*dicts: dict) -> dict:
    result: dict = {}
    for d in dicts:
        for k, v in d.items():
            if k in result and isinstance(result[k], dict) and isinstance(v, dict):
                result[k] = _deep_merge(result[k], v)
            else:
                result[k] = v
    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Collapse per-host Gentoo USE flag facts into group_vars / host_vars YAML.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--facts-dir",
        required=True,
        type=Path,
        help="Directory containing per-host JSON fact files.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        type=Path,
        help="Project root where group_vars/ and host_vars/ will be written.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be written; do not touch the filesystem.",
    )
    parser.add_argument(
        "--update",
        action="store_true",
        help="Merge with existing YAML files instead of overwriting.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    facts_dir: Path = args.facts_dir
    output_dir: Path = args.output_dir
    dry_run: bool = args.dry_run
    update: bool = args.update

    # --- Load facts ---------------------------------------------------------
    facts = load_facts(facts_dir)
    if not facts:
        sys.exit(1)

    all_hosts = sorted(facts.keys())
    group_map = build_group_map(facts)

    print(f"Loaded facts for {len(all_hosts)} host(s): {', '.join(all_hosts)}")
    print(f"Groups: {sorted(group_map.keys())}")
    if dry_run:
        print("[DRY-RUN] No files will be written.\n")

    # --- Preprocess: derive structured fields from make_conf_raw ------------
    preprocess_facts(facts)

    # --- Promote */* package.use entries into global_use_flags / use_expand ---
    promote_wildcard_package_use(facts)

    # --- Collapse each domain -----------------------------------------------
    all_accumulator: dict = {}
    group_accumulator: dict[str, dict] = defaultdict(dict)
    host_accumulator: dict[str, dict] = defaultdict(dict)

    for collapse_fn in (
        collapse_global_use,
        collapse_use_expand,
        collapse_build_profile,
        collapse_package_use,
        collapse_make_conf,
        collapse_use_flag_types,
    ):
        a, g, h = collapse_fn(facts, group_map, all_hosts)
        all_accumulator = _deep_merge(all_accumulator, a)
        for grp, data in g.items():
            group_accumulator[grp] = _deep_merge(group_accumulator[grp], data)
        for host, data in h.items():
            host_accumulator[host] = _deep_merge(host_accumulator[host], data)

    # --- Write output --------------------------------------------------------
    changed_count = 0

    # group_vars/all/
    if all_accumulator:
        out = output_dir / "group_vars" / "all" / "use_flags.yml"
        if _write_yaml(out, all_accumulator, dry_run, update):
            changed_count += 1

    # group_vars/<group>/
    for grp, data in sorted(group_accumulator.items()):
        try:
            _safe_path_component(grp, "group")
        except ValueError as exc:
            import logging
            logging.warning("Skipping group: %s", exc)
            continue
        out = output_dir / "group_vars" / grp / "use_flags.yml"
        if _write_yaml(out, data, dry_run, update):
            changed_count += 1

    # host_vars/<host>/
    for host, data in sorted(host_accumulator.items()):
        try:
            _safe_path_component(host, "host")
        except ValueError as exc:
            import logging
            logging.warning("Skipping host: %s", exc)
            continue
        out = output_dir / "host_vars" / host / "use_flags.yml"
        if _write_yaml(out, data, dry_run, update):
            changed_count += 1

    summary = "would change" if dry_run else "changed"
    print(f"\nDone — {changed_count} file(s) {summary}.")


if __name__ == "__main__":
    main()
